---
    - hosts: prod
      tasks:
        - name: Check Media-API cloned
          stat:
            path: /home/{{ lookup('env','USER') }}/Media-API
          register: media_api_cloned

        - name: Check if Media-API is cloned
          when: not media_api_cloned.stat.exists
          fail:
            msg: Media-API is not cloned. Please clone it first.
        
        - name: Check if cert.pem copied
          stat:
            path: /home/{{ lookup('env','USER') }}/Media-API/api/cert.pem
          register: cert_pem_copied
        
        - name: Check if key.pem copied
          stat:
            path: /home/{{ lookup('env','USER') }}/Media-API/api/privkey.pem
          register: key_pem_copied
        
        - name: Check if cert.pem and key.pem are copied
          when: not cert_pem_copied.stat.exists or not key_pem_copied.stat.exists
          fail:
            msg: cert.pem and key.pem are not copied. Please copy them first.
        
        - name: check nginx
          stat:
            path: /etc/nginx/sites-enabled/{{ lookup('env','MEDIA_API_DOMAIN') }}
          register: nginx_enabled
        
        - name: check nginx
          when: not nginx_enabled.stat.exists
          fail:
            msg: nginx is not enabled. Please enable it first.
          
        - name: Recontainerise
          shell: |
            cd /home/{{ lookup('env','USER') }}/Media-API
            docker-compose up --build -d