name: Make Image and push it to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set time 
      id: time
      uses: Kaven-Universe/github-action-current-date-time@v1.1.0
      with:
        format: "YYYY_MM_DD HH_mm_ss_SSS"
    - uses: actions/checkout@v3
    - name: Print time
      run: echo ${{ steps.time.outputs.time }}
    - name: Login to Dockerhub
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/media-api:${{ steps.time.outputs.time }}
    - name: Push to Docker Hub
      run: docker push ${{secrets.DOCKER_USER}}/media-api:${{ steps.time.outputs.time }}
